


import AuthProvider from '@/GlobaState'
import './globals.css'



export const metadata = {
  title: 'Life Changers',
  description: 'Generated by create next app',
}
if (typeof window !== 'undefined') {
  // Your window-dependent code here
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>



      </body>
    </html>
  )
}
